apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: alpine-nginx-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: alpine-nginx
    spec:
      containers:
        - name: alpine-nginx
          image: alpine-nginx
          imagePullPolicy: Never
